package game

var ALL_STICKER_TAGS = []string {
    "pinapple-house",
    "lipstick",
    "blood-splash",
    "beer",
    "creeper",
    "coffin",
    "fire",
    "dirty-dishes",
    "sword",
    "saxophone",
    "tardis",
    "pinata",
    "groucho",
    "money-briefcase",
    "rubber-duck",
    "pride-flag",
    "cthulu-oct",
    "lollipop",
    "explosion",
    "dynamite",
    "banana-peel",
    "pile-of-poop",
    "eggplant",
    "skull-flag",
    "chicken",
}

